### ISSUE TITLE
libpng warning: iCCP: known incorrect sRGB profile

### ISSUE THREAD

**Issue by aiskuld** [sourabhv/FlapPyBird#12]
When running, I get warnings every few seconds from libpng. Apparently, it's an issue with the iCCP chunk of the png image. Hasn't caused any real issues, though

**Comment by roachsinai** [comment]
Goto `assets/sprites` and Run `mogrify *.png`.

https://stackoverflow.com/a/22747902/6074780

**Comment by sourabhv** [comment]
fixed :)
