### ISSUE TITLE
Make exe using setup.py

### ISSUE THREAD

**Issue by sourabhv** [sourabhv/FlapPyBird#2]
py2exe doesn't seem to work well on 64 bit windows (`'bundle_files': 1` doesn't support win64 for now). So, it would be great if someone can use their 32 bit windows and create an exe. Feel free to change `setup.py`.

Use _python27_, _pygame 1.9.X_

**Comment by BatDev0** [comment]
Also, do this for mac.

Python27, pygame 2.0.0.dev4
