### ISSUE TITLE
Forked Repo

### ISSUE THREAD

**Issue by BatDev0** [sourabhv/FlapPyBird#25]
Since the owner of this repo isn't active, I will be forking it and anwsering any issues/questions.

Forked repo: [forked repo](https://github.com/BatDev0/FlapPyBird)

@sourabhv

**Comment by sourabhv** [comment]
If yo wanna help out with this one, I'd be happy to add you as collaborator

**Comment by BatDev0** [comment]
I would love to help. Ill happily help with this amazing project.

**Comment by sourabhv** [comment]
Done! Thanks for the help
