### ISSUE TITLE
Possible addition

### ISSUE THREAD

**Issue by tpapavas** [sourabhv/FlapPyBird#33]
How about adding mute button? The sound may be a little tiring for some people. I would love to give it a try.

**Comment by sourabhv** [comment]
Sure, should be simple enough, a simple pixel style speaker icon on home screen which sets a boolean. Give it a go.

The sounds are played using `SOUNDS` dict. `SOUNDS['wing'].play()`

So move all these instances to a function and in there check for mute toggle

**Comment by UjjwalSaini07** [comment]
Yes i also Satisfied with the thoughts given by @tpapavas here mute button is mandatory to mute the volume bcq some person not love to hear noise.
