### ISSUE TITLE
Bird going outside the window(on top) not ending the game?

### ISSUE THREAD

**Issue by thesmartdeveloperr** [sourabhv/FlapPyBird#36]
Why is  so? Is that intended in the code? and can it be improved?
**My OS:** MacOS Big Sur
**Python Version:** 3.9.4

The game is working fine but just had this issue. pls clarify...

**Comment by sourabhv** [comment]
Don't remember this exactly, I remember it can to at max 1 bird height outside and that doesn't end the game (which is fine).

 If it goes well beyond that limit, can you fix it and make a PR?

**Comment by UjjwalSaini07** [comment]
If bird goes Outside the window the game terminates as game ended means at apex level of game of window their is a wall as same as ground so if bird collide with it the **Game Ends**

**Comment by sourabhv** [comment]
This repo is not being maintained by me (or anyone) anymore. But feel free to fix this and make a pr. I will gladly review it.
